# HW4 

## 用物件導向的方式，建立屬於自己的normal scaler（標準化），

## 其中要包含fit及transform功能

# PART1

In [1]:
from sklearn.preprocessing import StandardScaler

data = [[0, 0], [0, 0], [1, 1], [1, 1], [0, 1]]
scaler = StandardScaler()
print(scaler.fit(data))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [4]:
print(scaler.mean_)
print(scaler.var_)

[ 0.4  0.6]
[ 0.24  0.24]


In [5]:
print(scaler.transform(data))

[[-0.81649658 -1.22474487]
 [-0.81649658 -1.22474487]
 [ 1.22474487  0.81649658]
 [ 1.22474487  0.81649658]
 [-0.81649658  0.81649658]]


In [6]:
print(scaler.transform([[2, 2]]))

[[ 3.26598632  2.85773803]]


# PART2

In [7]:
import numpy as np
import pandas as pd

In [27]:
class part2:
    def __init__(self):
        self.data_mean_ = None
        self.data_var_ = None
        
    def fit(self,data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_var_ = np.var(data, axis=0)
        self.data_std_ = np.std(data, axis=0)
        
    def transform(self,data):
        std_data = (np.array(data)-self.data_mean_)/np.sqrt(self.data_var_)
        return std_data
    
    def fit_transform(self,data):
        self.fit(data)
        return self.transform(data)

In [28]:
part2 = part2()

In [29]:
part2.fit(data)

In [30]:
part2.data_mean_

array([ 0.4,  0.6])

In [31]:
part2.data_var_

array([ 0.24,  0.24])

In [32]:
part2.data_std_

array([ 0.48989795,  0.48989795])

In [33]:
part2.transform(data)

array([[-0.81649658, -1.22474487],
       [-0.81649658, -1.22474487],
       [ 1.22474487,  0.81649658],
       [ 1.22474487,  0.81649658],
       [-0.81649658,  0.81649658]])

In [36]:
part2.fit_transform(data)

array([[-0.81649658, -1.22474487],
       [-0.81649658, -1.22474487],
       [ 1.22474487,  0.81649658],
       [ 1.22474487,  0.81649658],
       [-0.81649658,  0.81649658]])